Name:           ros-melodic-prosilica-camera
Version:        1.9.4
Release:        1%{?dist}
Summary:        ROS prosilica_camera package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/prosilica_camera
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-camera-calibration-parsers
Requires:       ros-melodic-diagnostic-msgs
Requires:       ros-melodic-diagnostic-updater
Requires:       ros-melodic-driver-base
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-polled-camera
Requires:       ros-melodic-prosilica-gige-sdk
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-self-test
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
BuildRequires:  ros-melodic-camera-calibration-parsers
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-diagnostic-updater
BuildRequires:  ros-melodic-driver-base
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-polled-camera
BuildRequires:  ros-melodic-prosilica-gige-sdk
BuildRequires:  ros-melodic-rosconsole
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-self-test
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs

%description
A ROS driver node for AVT/Prosilica Gigabit Ethernet (GigE) cameras.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Apr 26 2019 Austin Hendrix <namniart@gmail.com> - 1.9.4-1
- Autogenerated by Bloom

